chroma:
  collection_name: product_assistant
  persist_directory: ./chroma_db

retriever:
  top_k: 3

embedding_model:
  provider: "aws"
  model_name: "amazon.titan-embed-text-v2:0"

llm:
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-120b"
    temperature: 0
    max_output_token: 2048
  openai:
    provider: "openai"
    model_name: "gpt-4o-mini"
    temperature: 0
    max_output_token: 2048